### ISSUE TITLE
throw error on vapor 1.0

### ISSUE THREAD

**Issue by cheft** [mckomo/gulp-vapor#1]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn .build/debug/App ENOENT
    at exports._errnoException (util.js:896:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mckomo** [comment]
Thanks for submitting this issue. As you already noticed, this problem is related to the Vapor update to 1.0 version. Tomorrow I'm planning to start new branch vapor-10 and fix same update for newest vapor version.
